import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/about.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="author" content="MDIA 2109"/>
        <meta property="og:title" content="Assignment #1 - About Us Page"/>
        <meta property="og:description" content="BCIT Digital Design and Development Diploma"/>
        <link rel="icon" href="/favicon.png"/>
      </Head>

      <main className={styles.main}>
      <div className={styles.description}></div>

      <div>
        <h1>About Us</h1>
        <h1>DEPARTMENTS</h1>
      </div>

      <div>
        <p>We are proud to deliver an education that goes beyond textbooks and classrooms.</p>
        <p>Our students gain the technical skils, real-world experience, and problem-solving ability needed to embrace complexity and lead innovation in a rapidly changing workforce.</p>
        <p>Through close collaboration with industry, our network of alumni and partners continue to achieve global success.</p>
        <p>Information sessions are a simple way to figure out the next step along your career path.</p>
        <p>Learn more about the programs that interest you.</p>
        <p>Big Info is the largest program expo and information session at BCIT. It's your chance to find out about all our programs - from business, computing, and health to engineering, trades, and applied sciences.</p>
        <p>If you missed our fall event the next Big Info is scheduled to return on February 15, 2023.</p>
      </div>

      <div>
        <h2>Information Sessions</h2>
        <h2>Campus Tours</h2>
      </div>
      
      <div>
        <h3>Big Info</h3>
      </div>


      <img src="/icons/leftArrow.png"></img>
      <img src="/icons/rightArrow.png"></img>

      <ul>
        <li>Applied & Natural Sciences</li>
        <li>Business & Media</li>
        <li>Computing & IT</li>
        <li>Engineering</li>
        <li>Health Sciences</li>
        <li>Trades & Apprenticeships</li>
      </ul>

      <a>
        <span>
          <img></img>
          <img></img>
        </span>
      </a>
      </main>
    </>
  )
}
