import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Bg from 'public/background-images/backgroundMountain.jpg'
import downArrow from 'public/icons/downwardArrow.png'
import grad from '@/components/grad'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="MDIA 2109" />
        <meta property="og:title" content="Assignment #1 - Home Page" />
        <meta property="og:description" content="BCIT Digital Design and Development Diploma" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Image src={Bg} fill
        style={{
          zIndex: -1
        }}
      />

      <main className={styles.main}>

        <div className={styles.nav}>
          <hamburger></hamburger>
          <gradHat></gradHat>
        </div>

        <div className={styles.mainInfo}>
          <div className={styles.mainHeader}>
            <h1>An investment in <br />
              knowledge pays the best <br />
              interest.</h1>
            <div className={styles.mainLine}></div>
          </div>

          <p>Different than a college or university, the British Columbia <br />
            Institute of Technology offers practical, flexible, applied <br /> education with instructors who have direct, hands-on <br />
            experience in their field.</p>

          <a className={styles.aButtons}>
            <button
              className={styles.buttons}
              onClick={() =>
                router.push('/about')
              }>
              More About Us
            </button>

            <button
              className={styles.buttons}
              onClick={() =>
                router.push('/contact')
              }>
              Contact Us
            </button>
          </a>

        </div>



        <a className={styles.downArrow} href="/about">
          <span>
            <Image src={downArrow} width={40} height={50} />
          </span>
        </a>
      </main>
    </>
  )
}
